### ISSUE TITLE
magento 2 data migration tool Integrity constraint violation:

### ISSUE THREAD

**Issue by myselfgaurav** [magento/data-migration-tool#170]
i am trying to data importn , my import got stopped with below error :

as i think it is due to some duplicate value but can you guide which table should i check and fix . Please guide me way to fix it 

    [INFO][mode: data][stage: data migration][step: EAV Step]: started
    71% [====================>-------] Remaining Time: 1 sec
    
      [PDOException]
      SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '136' for key 'PRIMARY'

**Comment by victor-v-rad** [comment]
Thank you for reporting the issue. We will investigate this within internal MAGETWO-59805

**Comment by ygrigoriev** [comment]
Hello @myselfgaurav,

There are two errors on the way of your database and both of them concern to data consistency:
- Records `catalog_eav_attribute`.`attribute_id` IN (132,133,134,135,136,137) should be removed before migration since there are no attributes with such IDs in `eav_attribute` table
- Records `eav_entity_attribute`.`entity_attribute_id` IN (130,131,132,133,134,135) should be removed before migration since there is no attribute group with `attribute_group_id`=18 and also no attributes with IDs referenced by these records

**Comment by myselfgaurav** [comment]
Fine thanks will check with you suggestions , also is there way to detect
these types of issue . so any user facing these issue  can fix by them self
of idea of bug.

**Comment by victor-v-rad** [comment]
Sure. The tool in future should take into account such issue with data integrity.
