### ISSUE TITLE
Integrity Constraint violation for key EAV_ENTITY_ATTRIBUTE_ATTRIBUTE_SET_ID_ATTRIBUTE_ID

### ISSUE THREAD

**Issue by shy7lo** [magento/data-migration-tool#201]
I am trying to import data to M 2.1.2 from M 1.9.2.2. 
Whenever I run the migration command, i get the error as displayed in the attached screenshot. 

<img width="695" alt="screen shot 2016-12-11 at 12 55 55 pm" src="https://cloud.githubusercontent.com/assets/19299780/21079369/6a0e9a9e-bfa1-11e6-8068-c0ce8a8aa670.png">

I feel like the issue is in the eav_entity_attribute data insert. 

I am not exactly sure what is wrong in my EAV data. Can you please help me out here? 

Thank you

**Comment by victor-v-rad** [comment]
Try to restore your DB of Magento 2 to the state it was right after installation and run migration again

**Comment by shy7lo** [comment]
Thanks for your response. I just did a fresh Magento 2.1.2 installation and then installed Data Migration tool 2.1.2 and did all settings and mapping, and I am receiving the same error. 
I am still not sure what is going on there and why it is generating this error.

**Comment by shy7lo** [comment]
Any comments about this issue please? 

Thank you

**Comment by coresh** [comment]
### The same issue:
```
 [PDOException]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '25-303' for key 'EAV_ENTITY_ATTRIBUTE_ATTRIBUTE_SET_ID_ATTRIBUTE_ID'
```

**Comment by victor-v-rad** [comment]
Hi @coresh 

Thank you for the details. I have manage to reproduce the "Duplicate entry" error with your eav_entity_attribute dump. Though I got '4-137' as duplicated records still I think it have the same root cause. So internal ticket MAGETWO-62672 was created to fix it

**Comment by shy7lo** [comment]
Thanks for creating the internal ticket. Can you confirm if this issue is fixed in 2.1.3? 

Thank you

**Comment by victor-v-rad** [comment]
It wasn't. The problem is in \Migration\Step\Eav\Data::processDesignEntityAttributes method try to comment/remove it and after migration open original 'Default' attribute set in Magento 2 and find 'Schedule Design Update' group. You should manually add the same group and its attributes to migrated attribute sets from Magento 1

**Comment by coresh** [comment]
Hi @victor-v-rad, thanks for your complete reaction

**Comment by victor-v-rad** [comment]
@coresh @shy7lo It seems provided dump of eav_entity_attribute table is not enough to understand the whole picture. The EAV step processes the next tables:
eav_attribute_group
eav_attribute_set
eav_attribute
eav_entity_attribute
catalog_eav_attribute
customer_eav_attribute
eav_entity_type 
These are also needed to resolve the issue. You can put it here or email me (find email address in my profile https://github.com/victor-v-rad)

**Comment by shy7lo** [comment]
Hi Victor, 
I have just emailed you dump for all those tables. 

Thank you

**Comment by diazwatson** [comment]
Same issue here with magento/data-migration-tool": "2.1.3"

**Comment by victor-v-rad** [comment]
Hi @diazwatson 

I could not reproduce it. The root cause has not been found so far. I suggest you to find differences between the structure attribute sets of your Magento 1 store and Magento 1 in its initial state right after installation. Maybe these differences could have caused the error. 
Another way to solve the issue is to send me your DB (if it's not too big and free from sensitive data). I will try to reproduce it on my env. and fix it.

**Comment by avra911** [comment]
It seems that it depends on some particular attributes.
For us is trying to create `Baby / Child SS17` attribute set and gives `Integrity Constraint violation for key`.

Is not that simple to reproduce @victor-v-rad

**Comment by shy7lo** [comment]
# Note: I am not promoting this module

After wasting a lot of time on this issue and nothing to fix it including the support here, I decided to for this module 

https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/
 
It worked for me and everything was moved smoothly. I know it is expensive, but it is worth time saving and the hard efforts.

**Comment by alex-borisenko** [comment]
Problem is here https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Eav/Data.php#L642

**Comment by BartoszSiemienczuk** [comment]
Still the same problem on 2.2.2, @alex-borisenko tip did not help me at all. I even have tried to disable the constraint in question, but it fails on next - probably causing domino effect. I don't understand why this issue is closed.

**Comment by Lez-2** [comment]
I got this same issue while migrating from 1.7 to 2.2.2
I "fixed" this by renaming the Default attribute set in my Magento 2.2.2 instance back to "Default" (I had changed it's name before migration).
It's a weird solution, I know, but it worked in my case...

This idea came to mind because I noticed that after migration the attribute set IDs were imported from M1 with their original IDs, while the M2 defaults got their IDs "bumped up".
So the default attribute set id from M2 was changed to id = 21.
And in my case the "duplicate entry" was "21-152" which results to attribute_set_id = 21 and attribute_id = 152 which didn't exist in my M1 instance.
Maybe this might help others as well...

**Comment by MihaiTudorRO** [comment]
in my case database repair tool for source database it was best solution.
https://docs.magento.com/m1/ce/user_guide/magento/database-repair-tool.html

Follow steps and always backup backup

Hope that helps

**Comment by dambrogia** [comment]
Still experiencing this in 2.2.6

    [PDOException]
    SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-338' for key 'EAV_ENTITY_ATTRIBUTE_ATTRIBUTE_SET_ID_ATTRIBUTE_ID'

Looking at `migrateEntityAttributes()` in [data-migration-tool/blob/2.2.6/src/Migration/Step/Eav/Data.php](https://github.com/magento/data-migration-tool/blob/2.2.6/src/Migration/Step/Eav/Data.php#L468):

I can see that `$this->helper->getSourceRecords($sourceDocName)` will add records to the collection that will be added to the destination (m2) database.

Further down I can see that `$this->helper->getDestinationRecords('eav_entity_attribute')` gets records from the destination(?) and adds them again. From the looks of the code that's what it looks like is going on, but I have a fresh m2 install and there are no records inside the destination (m2) db. So while it _looks_ like this is what's going on. It's hard to believe my perception is the truth. 

The error I have for `4-338` pertains to the unique pair of columns `attribute_set_id` (4) and `attribute_id` (338). I can confirm in my source (m1) database that there is only one unique pair of this, but within the second foreach loop with `$this->helper->getSourceRecords($sourceDocName)`, another `attribute_set_id` & `attribute_id` combination is being added which is throwing this error.

Does anyone have any info on why this is happening and how to fix/prevent it?

**Comment by victor-v-rad** [comment]
Hi @dambrogia 

It is hard to figure out why duplicate happens. If it is possible, you can send dump of the next tables
```
    <group name="documents">
        <document>eav_attribute_group</document>
        <document>eav_attribute_set</document>
        <document>eav_attribute</document>
        <document>eav_entity_attribute</document>
        <document>catalog_eav_attribute</document>
        <document>customer_eav_attribute</document>
        <document>eav_entity_type</document>
    </group>
```
To [my email](https://github.com/victor-v-rad). I will try to migrate and reproduce the issue

**Comment by dambrogia** [comment]
@victor-v-rad thank you for the response. It turned out that @alex-borisenko answer was the solution. `attribute_id` 338 was the layout attribute_id. Adding that extra conditional to my if statement prevented the duplicate `4-338` pair from being added. 

Thanks for checking in on my status. FWIW I'm using the 2.2.6 migration tool.

**Comment by victor-v-rad** [comment]
This issue appears after creating a new attribute set in M2 based on "Default" attribute set **before** migration. It is recommended to migrate to the clean M2 store (without new entities). Anyway the fix from @alex-borisenko [comment ](https://github.com/magento/data-migration-tool/issues/201#issuecomment-361440309) works.

**Comment by dambrogia** [comment]
My problem was solved so I'm a happy camper. But just a heads up I was receiving this error on a fresh m2 install. Anyways, thanks for your help and support. It is much appreciated!
