### ISSUE TITLE
Typo in error message "Table <tablename> is not exists"

### ISSUE THREAD

**Issue by fwolfst** [magento/data-migration-tool#242]
... should read "does not exist".

I'll investigate the "real" issue (not having a typo would be cool, not having that error even cooler) and open a separate issue for it.

Applies to 2.1.4, migrate from 1.6.2 .

For reference:
[2017-02-13 08:47:41][INFO][mode: data][stage: data migration][step: Map Step]: started
27% [=======>--------------------] Remaining Time: 29 secs
  [Zend_Db_Exception]                    
  Table "customgrid_grid" is not exists

**Comment by victor-v-rad** [comment]
Thank you @fwolfst for reporting this issue. I believe the grammar error derives from Magento Framework rather than Migration Tool. The cause of the error is not clear because your customgrid_grid is ignored in map file and [clearDocument](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Map/Data.php#L140) should not be run.

**Comment by fwolfst** [comment]
Thanks victor!
Can you report upstream (or should I)? I believe the source of the error is that I disabled integrity checks, and customgrid_* is NOT in the map file.

**Comment by victor-v-rad** [comment]
I guess I once came across this typo among Magento 2 GitHub issues

**Comment by fwolfst** [comment]
Couldnt find it, so created a new issue and closing here.
