### ISSUE TITLE
Import with condition possible?

### ISSUE THREAD

**Issue by petrich** [magento/data-migration-tool#246]
Hi There, 

is it generally possible to migrate datas with some conditions?

In my case, i have multiple Websites/Shops/Customer Groups/Orders and i have to import them "time-splitted".

So i need to import the first group of Customers/Products/Websites/Orders first (skiping the "rest")... and after some weeks the "rest" (Delta Import).

Maybe someone can give me some tips how to configure or add api-classes to the migration-tool how to realize it.

(Full Migration works fine after some try & error and configuring the *.xml's project-based)
 
Thank you in advance
Greetings
Hans-Jürgen Petrich

**Comment by victor-v-rad** [comment]
Hi @petrich 

The tool was developed to migrate all at once. However you can stop migration (in the middle for example) by CTRL-C and rerun whenever you need. It will start migration from the point it was stopped.

**Comment by petrich** [comment]
Thank you for your reply. 

I will then make the "full import" 
and after that, deleting (via MAGE API) the "to-skip" Customers/Products/Orders... 
and after n-weeks doing a delta import ...

I think this will effectively have the same effect as a  "condition import"

Thank you again for your answer.
Greetings

**Comment by sb-rustam** [comment]
Hi @petrich,

I was so excited when I saw your post, because it was related (similar) to our data migration process. Here is our overall data migration plan:

Currently we are in process of migrating our Magento 1.14.3.8 websites into Magento 2.2.3 platform. We have 3 running websites under one Magento 1.x instance, each website has it’s own customers, products and orders. The plan was to migrate and launch these websites in phase approach (one by one). For example:

Website-1 will be launched in May 
Website-2 will be launched in August 
Website-3 will be launched in December

The current Magento 1.14.3.8 instance will be running until all of these websites will be migrated over to Magento 2.x.x. For example, once the website-1 will be launched in Magento2 the website-2 and 3 will still be running on Magento 1.14.3.8 instance and so on. This Magento 1.14.3.8 instance will be stopped once all of these 3 websites will be moved/launched in Magento 2.

I was wondering if I can run Magento data migration tool prior to launching the website-1, which should migrate the following data for all of these 3 websites, at once:

- stores/websites settings 
- the main data (like customers, orders, products and etc.)

and I want to keep running the delta migration until all 3 of these websites will be launched in Magento2.

Would you please advise me if this would be possible? If this approach doesn't work, then would you please provide more info regarding to potential issues or any workarounds?

Thank you in advance,
Rustam.
