### ISSUE TITLE
Deltalog for customer_entity is not installed. 

### ISSUE THREAD

**Issue by rajansahota** [magento/data-migration-tool#347]
Ready to go live with magento 2.1.7 on a staging server after successfully migrating a few weeks ago from Magento ver. 1.6.2.0

Trying to update with new customers and recent orders in the past few weeks since migration.

After trying the migrate:delta command.

[2017-08-14 07:06:22][INFO][mode: delta][stage: delta delivering][step: Customer Attributes Step]: started
[2017-08-14 07:06:23][ERROR]: Deltalog for customer_entity is not installed

@victor-v-rad 
please help.

**Comment by victor-v-rad** [comment]
Hi @rajansahota 
Look for the solution in #306

**Comment by Steelfirebat** [comment]
Hi Victor,

I have been reading alot here, but never posted.  So I am not sure if I suppose to reply to a closed post or open a new one since my problem is exactly like this one.

The different is my migration tool is version 2.1.8 so it already included that:
$destinationDocName = $this->destination->addDocumentPrefix($destinationDocName);

in the helper file.  Yet, I still have the problem:

[2017-11-17 17:52:09][INFO][mode: delta][stage: delta delivering][step: Customer                              Attributes Step]: started
[2017-11-17 17:52:09][ERROR]: Deltalog for customer_entity is not installed


  [Migration\Exception]
  Delta delivering failed


Here is my situations:

I have a live server running M1 and a separate server installed M2.  I have completed the migrations step (except for the Delta step) a few months back by making a copy of our M1 database into our M2 server.  Now that we are ready to go live and I needed to do the Delta migration by making a new copy of our M1 server over the same (old migrated) M1 database in our M2 server.  Look like this action have removed whatever table the tool made to M1 database while performed the migration before?

Can you please help?

Don

**Comment by sohrobdevise** [comment]
Hi @Steelfirebat ,

I am experiencing the same issue as you. What was your solution to resolve this?

Thanks,
