### ISSUE TITLE
Unable to unserialize value.

### ISSUE THREAD

**Issue by myselfgaurav** [magento/data-migration-tool#410]
after i am done with migration gettting error while editing products, pls help with issue

**Comment by victor-v-rad** [comment]
Hi @myselfgaurav 

What is the version of the tool you used? Were there any errors along migration? What is the error you get on the editing product page?

**Comment by es11support** [comment]
I'm seeing a similar issue on our Magento 2.2.0 install, using version 2.2.0 of the data migration tool.

The data was migrated successfully, but we noticed a missing "Add to Cart" button when viewing any product details.  I went back into the Configuration page to check/uncheck the "Manage Stock" option (as outlined in a stack overflow post about a way to possibly fix the missing button), but the "Configuration" page under "Catalog" -> "Inventory" page is blank (no settings on the right, but the left-hand menu is still there) - here is a screenshot of the page:

https://www.dropbox.com/s/zj29qczefollsi6/magento-config-blank.jpg?dl=0

Looking into it further, I can get the following error to trigger in "system.log" when I go to that page in the Configuration:

[2017-11-15 15:06:31] main.CRITICAL: Unable to unserialize value. [] []

When I looked up this error, I found another stack overflow post about a way to temporarily "trick" the "/vendor/magento/framework/Serialize/Serializer/Json.php" file to allow it to save properly:

https://magento.stackexchange.com/a/198109

...which I thought would bring the Configuration page back, but it instead now just completely blanks out.  The "Add to Cart" button was there before the migration, it only disappeared since the migration happened - where do I start with debugging this?

**Comment by myselfgaurav** [comment]
Hi solved issue by below way 

1: When I looked up this error, I found another stack overflow post about a way to temporarily "trick" the "/vendor/magento/framework/Serialize/Serializer/Json.php" file to allow it to save properly:

2: after that it was show some php error in one of file , i just put static value of minqty variable there as 1.

solved issue for me , but this wasted too much time :(

**Comment by es11support** [comment]
Yep - it came down to an issue with the values for some settings not converting to JSON properly:

https://github.com/magento/data-migration-tool/issues/401

Re-importing the settings after applying that patch worked.

**Comment by victor-v-rad** [comment]
Seems the issue is solved

**Comment by saminforca** [comment]
I did migration from 1.9 to Magento 2.2.6. 

I have implemented the step mentioned in this thread https://github.com/magento/data-migration-tool/issues/410#issuecomment-418055832

I am still having the same issue.

I am getting this error when I am browsing and any product from the frontend.

Any help is highly appreciated.

Regards,
Sam

**Comment by myselfgaurav** [comment]
i do not thing there is any issue please make sure u are following process correctly

**Comment by saminforca** [comment]
`<?php

namespace Ufm\General\Serialize\Serializer;

class Json extends \Magento\Framework\Serialize\Serializer\Json
{


    /**
     * {@inheritDoc}
     * @since 100.2.0
     */
    public function unserialize($string)
    {
      if($this->is_serialized($string))
        {
            $string = $this->serialize($string);
        }
        $result = json_decode($string, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
             throw new \InvalidArgumentException('Unable to unserialize value.');

        }
        return $result;
    }


    public function is_serialized($value, &$result = null)
    {
    // Bit of a give away this one
        if (!is_string($value))
        {
            return false;
        }
        // Serialized false, return true. unserialize() returns false on an
        // invalid string or it could return false if the string is serialized
        // false, eliminate that possibility.
        if ($value === 'b:0;')
        {
            $result = false;
            return true;
        }
        $length = strlen($value);
        $end    = '';
        switch ($value[0])
        {
            case 's':
                if ($value[$length - 2] !== '"')
                {
                    return false;
                }
            case 'b':
            case 'i':
            case 'd':
                // This looks odd but it is quicker than isset()ing
                $end .= ';';
            case 'a':
            case 'O':
                $end .= '}';
                if ($value[1] !== ':')
                {
                    return false;
                }
                switch ($value[2])
                {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                    case 7:
                    case 8:
                    case 9:
                        break;
                    default:
                        return false;
                }
            case 'N':
                $end .= ';';
                if ($value[$length - 1] !== $end[0])
                {
                    return false;
                }
                break;
            default:
                return false;
        }
        if (($result = @unserialize($value)) === false)
        {
            $result = null;
            return false;
        }
        return true;
    }
}

?>`

I did via custom extension development and I have confirmed that code file is called but the exception and error issue same even after implementation.

Let me know if you have any suggestion

Thanks
