### ISSUE TITLE
Notice: Undefined index: jobs

### ISSUE THREAD

**Issue by dm8mydog** [magento/data-migration-tool#454]
related to MAGETWO-66365: Exception Undefined index: jobs while running cron jobs

here's another old path value that slipped through the cracks: crontab/jobs/system_backup

why not make it ignore all?  crontab/jobs/.*

**Comment by victor-v-rad** [comment]
Hi @dm8mydog 

Thank you for posting this issue. Internal ticket MAGETWO-87699 for fixing it

**Comment by roma-glushko** [comment]
@victor-v-rad can we add some ignore rule for this issue line one @dm8mydog has already mentioned? Probably this would be helpful to close the question. 

I've experienced it as well (on Data Migration Tool 2.2.3) because of 3rd party modules that are installed on Magento 1 and they have their own cron schedules. They starts from `crontab/jobs/*` and it would be great if the framework handles them.

**Comment by carlos-reynosa** [comment]
I'm getting this issue still.
