### ISSUE TITLE
magento migration from 1.9.3.1 to 2.2.3 : customer_address_entity_static' doesn't exist 

### ISSUE THREAD

**Issue by areyasad** [magento/data-migration-tool#478]
I am getting this error when migrating from magento 1.9.3.1 to magento 2.2.3 

  [Zend_Db_Statement_Exception]                                                                                                                                                   
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'chansona_demo-new.customer_address_entity_static' doesn't exist,

I have check this table in source db , and it does not exist so why magento migration script is referring to this, how to solve this ?

**Comment by victor-v-rad** [comment]
Hi @areyasad 

It can be cache problem. You can try to reinstall Magento 2 and the tool from scratch and rerun migration.

**Comment by xeontcs** [comment]
Hi,

Did you solve this issue?

I get the exact same error.

Thank you.

**Comment by domeglic** [comment]
I had a similar problem but with `customer_entity`. The problem was that one of the attributes was changed to have backend_type=static.

Check this file for a list of non-static attributes that the tool will try to load: `/etc/opensource-to-opensource/customer-attribute-groups.xml.dist`. Now check if any of these are set to backend_type=static in the table `eav_attribute`. In my case the attribute middlename was set as static.

I don't know if this is true, but from what I see none of the attributes on that list should have backend_type=static otherwise the tool will attempt to load their values from the table `customer_address_entity_TYPE`

**Comment by xeontcs** [comment]
@domeglic Thank you!

I found this by dumping the data. I found the attributes which cause this issue.

I can migrate to a fresh M2 installation now.

But I'm having an issue when I tried to migrate data to a store which already built and design with some extensions.

I cleared all the sample data using https://gist.github.com/sjovanig/3c18d687c60bb39cd752ce63db5d72f7

The error I'm getting is,

[2020-07-03 14:17:17][INFO][mode: data][stage: data migration][step: EAV Step]: started
0% [>---------------------------] Remaining Time: < 1 sec
[2020-07-03 14:17:17][ERROR]: Not mapped id key 26 found for eav_entity_attribute.attribute_set_id

Any idea how to solve this issue?
