### ISSUE TITLE
Only a dot (.) at the end of requested path?

### ISSUE THREAD

**Issue by diazwatson** [magento/data-migration-tool#481]
I am using the tool to migrate data from 1.14.2.3 to 2.2.3
After `data` step is finished I noticed that all requested paths in the url rewrite table end with only a dot (.)

#### Configuration
![_mysql_5_6_38-83_0__localhost_pramworld_src_core_config_data](https://user-images.githubusercontent.com/1080386/37470267-1359a61c-285f-11e8-865b-9e969dbb102f.jpg)

#### Sample Urls
`brand/icandy/icandy-strawberr`

#### Sample Urls
`brand/icandy/icandy-strawberr.`

Has any body seen this before?

**Comment by victor-v-rad** [comment]
Hi @diazwatson 

Thank you for posting this issue. Internal ticket to fix this bug is MAGETWO-89312
As a hot fix you can try to change the line 
``` $suffix = $this->ensureSuffixBeginsWithDot($suffix);```
in [src/Migration/Step/UrlRewrite/Model/Suffix.php](https://github.com/magento/data-migration-tool/blob/2.2.3/src/Migration/Step/UrlRewrite/Model/Suffix.php#L85)
with 
``` $suffix = ($suffix) ? $this->ensureSuffixBeginsWithDot($suffix) : $suffix; ```

**Comment by diazwatson** [comment]
Thanks for your reply @victor-v-rad 
There is a PR with the changes in case you guys want to integrate it into the repo.

**Comment by victor-v-rad** [comment]
Thank you @diazwatson
