### ISSUE TITLE
[Migration\Exception] - Integrity Check failed [Magento 1.13.0.2 To Magento 2.1.8]

### ISSUE THREAD

**Issue by nguyetnguyen** [magento/data-migration-tool#490]
Hi support team, 
I got problem on migrating date from Magento EE 1.13.0.2 to Magento 2.1.8. Here is the error:

$ **php bin/magento migrate:settings -r vendor/magento/data-migration-tool/etc/ee-to-ee/1.13.0.2/config.xml**
Reset the current position of migration to start from the beginning

[2018-04-02 11:48:41][INFO][mode: settings][stage: integrity check][step: Settin
gs Step]: started
100% [============================] Remaining Time: 1 sec
[2018-04-02 11:48:41][INFO][mode: settings][stage: integrity check][step: Stores
 Step]: started
100% [============================] Remaining Time: 1 sec

  [Migration\Exception]
  Integrity Check failed

migrate:settings [-r|--reset] config

On checking migration.log. No error was thrown.

[2018-04-02 11:56:56][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
[2018-04-02 11:56:56][INFO][mode: settings][stage: integrity check][step: Stores Step]: started

Could you please help?

**Comment by victor-v-rad** [comment]
I assume there are additional fields (probably created by extensions) in tables related to stores and websites. (core_website, core_store, core_store_group tables) In Data Migration Tool 2.2.x this issue was fixed. You can try to use the latest Magento 2.2.3 and the latest tool 2.2.3 to resolve it. Or check these tables by your self and if the data of conflicting fileds you do not need in Magento 2 then remove 
`<integrity>Migration\Step\Stores\Integrity</integrity>` from your config.xml file and restart migration `settings`
