### ISSUE TITLE
Which version should we use to upgrade from 1.9 to 2.0.17?

### ISSUE THREAD

**Issue by jan1980** [magento/data-migration-tool#588]
Hi friends, we are using [Magento Open Source 2.0.17](https://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.17CE.html).

On the [docs](https://devdocs.magento.com/guides/v2.3/migration/migration-tool-install.html) they say we need to match Magento versions and the Data Migration Tool extension version (ie. 2.2.0 with 2.2.0), however on the [Releases](https://github.com/magento/data-migration-tool/releases) area we only find version 2.2.0 around the same dates Magento 2.0.17 was released.

Is this because we are talking about different Magento releases (the Open Source and the Paid Magento version)?

In that case, if we are using Open Source 2.0.17, which Release of the Data Migration Tool should we use?

Thanks,

**Comment by hostep** [comment]
@jan1980: you should be aware that the support for Magento Open Source 2.0 has already ended in March 2018, see [this document](https://magento.com/sites/default/files/magento-open-source-software-maintenance-policy.pdf), so it's not really a good idea to start a new Magento 2 shop on such an outdated version.

Nevertheless, you have a valid point, since certain versions which Magento does still support are missing an equivalent version of the data-migration tool (for example 2.1.10 and higher are missing).

**Comment by jan1980** [comment]
Thanks @hostep I'll go for 2.2.0 right away.
Just one question, from which 1.9 version is easier to upgrade?
Thanks!
