### ISSUE TITLE
Notice: Undefined index: dest

### ISSUE THREAD

**Issue by sufyaniksula** [magento/data-migration-tool#660]
### Preconditions

1. Migrating from magento 1.9.3.7 to magento 2.3.0, using LAMP environment, php7.2

### Steps to reproduce

1. Installed data migration tool using composer
2. Did the necessary configurations
3. Migrated settings successfully
4. Run the migrate:data command

### Expected result

1. Migration complete

### Actual result

1. Notice: Undefined index: dest in /var/www/html/magento/vendor/magento/da  
  ta-migration-tool/src/Migration/Step/Eav/InitialData.php on line 161

**Comment by sufyaniksula** [comment]
checked the mentioned file and it calls the below method:

`public function getAttributes($type)
    {
        return $this->attributes[$type];
    }
`

**Comment by sufyaniksula** [comment]
Checked on further and found its coming from data-migration-tool/src/Migration/Step/Eav/Data.php line 421

`$destinationRecords = $this->initialData->getAttributes('dest');`

**Comment by sufyaniksula** [comment]
In data-migration-tool/src/Migration/Step/Eav `initAttributes()` calls `getDestinationRecords()` which returns null for some reason.

**Comment by victor-v-rad** [comment]
Hi @sufyaniksula 

EAV is the first step in migration of data. Did you run migration of settings and if it was successful? Please recheck that your MySQL connection has all necessary Read/Write privileges

**Comment by sufyaniksula** [comment]
> Hi @sufyaniksula
> 
> EAV is the first step in migration of data. Did you run migration of settings and if it was successful? Please recheck that your MySQL connection has all necessary Read/Write privileges

The migration of settings was successfull. Also there is no problem with database connectivity as I can see entries in eav_attribute_set.

**Comment by sufyaniksula** [comment]
In data-migration-tool/src/Migration/Step/Eav/InitialData.php I checked the method initAttributes(). I printed $destinationRecords which is a null array for some reason. The $destinationRecords is initialised as : 
`$destinationRecords = $this->getDestinationRecords(
                $sourceDocument,
                ['entity_type_id', 'attribute_code']
            );
`
Due to this $this->attributes['dest'] is not being indexed.

**Comment by victor-v-rad** [comment]
You can use xdebug to find the root of the problem

**Comment by AJHopper** [comment]
@sufyaniksula Were you able to resolve this at all?

I'm having the exact same issue when trying to run it

**Comment by sufyaniksula** [comment]
There were a lot of issues in our Magento 1 database. But even after solving those this issue still comes. Have not able to find the root cause yet. There were attributes where the value of attribute_code was NULL in eav_attribute. We deleted those entries but that doesn't solve the issue.

**Comment by AJHopper** [comment]
@victor-v-rad 

Hey Victor, I have been doing a little bit of digging into this as i'm having this issue too.

From what I can see when it called the `protected function initAttributes()` within the InitialData.php for the EAV part of things.

```
$destinationRecords = $this->helper->getDestinationRecords(
                $sourceDocument,
                ['entity_type_id', 'attribute_code']
            );
```

this function is only returning 1 record, which means that ['dest'] is only getting set for the one record

whereas the source side of things is being populated correctly with all 205 record in my case. Im assuming that this should be a 1-1 relation with 205 results on both sides?

**Comment by AJHopper** [comment]
@victor-v-rad 

As an added note.. when looking at the contents of the items

the "source" side 205 records are populated like this

```
Array
(
    [attribute_id] => 567
    [entity_type_id] => 2
    [attribute_code] => password_created_at
    [attribute_model] =>
    [backend_model] =>
    [backend_type] => int
    [backend_table] =>
    [frontend_model] =>
    [frontend_input] => text
    [frontend_label] => Password created at
    [frontend_class] =>
    [source_model] =>
    [is_required] => 0
    [is_user_defined] => 0
    [default_value] =>
    [is_unique] => 0
    [note] =>
)
```

but the 1 "dest" side record is 
```
Array
(
)
```

**Comment by not-art** [comment]
I don't think this issue should be closed...

I'm having the exact same error on a test migration from Magento Commerce 1.14.4.0 to Magento Commerce 2.3.1. 

Is there an actual solution for this migration tool issue? Why is only 1 dest record being populated from the source records?

**Comment by victor-v-rad** [comment]
I cannot reproduce the issue on my local environment. @sufyaniksula @AJHopper @not-art if you were able to find root cause please share the information. Thank you.

**Comment by not-art** [comment]
Victor, is your local you tested against trying to migrate data from commerce to commerce, going from 1.14.4.0 ->2.3.1? I'm also using mysql 5.7 and php-fpm 7.2.11. This is the setup I was able to reproduce against.

As for root cause, I don't know. That's why I came here looking for a bug / issue that I was facing; this is the exact issue I'm facing. We get past our integrity checks, it starts the data migration for EAV, and bombs out for the exact above issue; 

Notice: Undefined index: dest in /var/www/html/magento/vendor/magento/da
ta-migration-tool/src/Migration/Step/Eav/InitialData.php on line 161

I'm unsure what data issues I could be having in my m1 environment that would cause the dest array to not populate with the necessary index; none of the mapping complaints relate to EAV issues.

I'll see if I can gather additional info that might help you replicate; for me this happens every time I reset my m2 database and re-try the data migration, so it's 100% reproducible in my migration tests, and we haven't done any major changes (or any that I'm aware of) to our M1 EAV model / data structure that would be causing the M2 migration to bomb out on this step.

**Comment by victor-v-rad** [comment]
If you use setup:uninstall command to "reset" Magento it will remove DB. You need restore Magento from DB backup of just installed Magento 2

**Comment by not-art** [comment]
I have not done the setup:uninstall to reset. I reset my db by restoring it. Each clean restore causes this issue at this same point of the migration.

Are you replicating against commerce to commerce, going from 1.14.4.0 ->2.3.1, using mysql 5.7, and 2.3.1 of the data migration tool? This could be version-specific. Please try replicating against the setup I'm having the issue with, if possible.

**Comment by pjw345** [comment]
I'm not sure this helps in anyway, but I had the same issue thinking it was caused by the migration tool, but in fact it was an attribute that was being created and immediately deleted in the M2 initial setup leaving in my case a rouge entry in the eav_entity_attribute table.

Without even starting the migration process, I did several clean installations of M2 2.3.1, i.e. new database, completely new composer installation of M2.   After running the first php bin/magento setup:install and a subsequent php bin/magento setup:upgrade, I checked the eav_attribute & eav_entity_attribute table and each time I had an additional entry on the eav_entity_attribute table with no corresponding eav_attribute entry,

In my case the attribute_id was always 151.  So in fact I had to perform a clean install, remove the rouge record from the eav_entity_attribute table and only then could I run my migration process.

In my opinion the migration process should not only check the source but also the destination tables before even starting or attempting the migration process.

**Comment by not-art** [comment]
Anything helps at this point, Paul- so thank you for giving me a thread to pull on. :)

Let me refresh my DB and do the usual post-install steps that you mentioned, but also clean/clear my eav_entity_attribute table with a truncate if need be, prior to migrating. I had tried truncating the tables as well, but perhaps there's some rogue data or rogue reference that I need to remove... 

Will check back in a bit with if it helped my scenario.

**Comment by AJHopper** [comment]
Have had a quick check on my end based on your suggestion Paul and it doesnt seem to be the case for my install at least (can take a more thorough look later). But it does make me think it could be something on the Magento 2 side of things so will spend some more time investigating. Should have time to work on it this weekend. 

If you guys figure anything else out before then though drop it on here please :)

**Comment by not-art** [comment]
Darn- thanks for trying AJ- since I had been truncating all EAV tables after restoring to be safe, I was not hopeful it'd work, but willing to try anything since this is 100% blocker on our data migration without any real leads as to why. 

Thanks for diving in as well- I'll report my findings here as I try various things today / tomorrow.

**Comment by not-art** [comment]
Our migration is running now, without doing anything that I can see to fix the original issue. What we did:

- Removed any magento sample data modules via composer remove
- Added magento sampledata:remove to our build to fully clean up the above-removed sample data composer references
- Deleted all "m2_cl" tables from our M1 staging database
    - We never did this on each re-try I mentioned above
    - Given that fully resetting our M2 database didn't help / wasn't helping, this is my guess at what fixed the issue... when we first ran the data migration tool, we had the mysql db go away AND then on next run, the docker container running the migration died. My hunch is one of these errors likely died mid-write to one of the m2_cl tables, causing some corrupt data or incomplete source info. Thus, on subsequent runs- despite refreshing our M2 db to install-state or passing the -r flag, the migration was getting an incomplete source/dest index match for EAV

Once I completed the above 3 steps, our migration started and got past the EAV migration. It wound up dying later-on during the Customer Attributes Step in the migration, due to exceeding max_allowed_packet (which I have set to 4mb), but changing bulk_size from 0 to 100 in our config.xml seems to have been the trick to avoid exceeding max_allowed_packet size.

Sorry for the confusion / red herrings, Victor, and best of luck Paul / AJ.

**Comment by fuzzyegg** [comment]
Check that your destination EAV tables have data in. I ran into this issue when attempting to migrate to a schema with no initial data in.

If you look at vendor/magento/data-migration-tool/src/Migration/Step/Eav/InitialData.php on line 108, when initialising the attributes the 'dest' index will not be set if you have no attributes in your EAV table.

```
        foreach ($destinationRecords as $id => $record) {
            $this->attributes['dest'][$id] = $record;
        }
```

A simple fix is to ensure you've run the Magento 2 install for your site before running the migration, which will add the base attributes for you.
