### ISSUE TITLE
Cannot Save Product after Full migration, "No Such Entity"

### ISSUE THREAD

**Issue by jambardnishvili** [magento/data-migration-tool#672]
### Preconditions

1. Magento 2.3.0, PHP 7.2 MySQL 5.7.25

### Steps to reproduce

1. Do Full migration of store
2. Try to Change something in product and save

### Expected result

1. Save Product successfuly

### Actual result

1. [Screenshot, logs]
It throws "No such entity" Error

So, after debugging i found it's an issue of trying to get store group by id which doesn't exist in store_group table
![Screenshot from 2019-04-01 16-54-44](https://user-images.githubusercontent.com/43703698/55329124-e9778180-549e-11e9-84d6-0de3845956ac.png)
Here it's trying to get store by group_id 3 
![Screenshot from 2019-04-01 16-56-23](https://user-images.githubusercontent.com/43703698/55329216-1af04d00-549f-11e9-90e7-af4aa7251987.png)
This is the place it's trying to get from, as you can see 3 does not exist there, it's not in database table store_group aswell which is where these values are gotten from, this record exists in store table which has group_id 3 and it's is_active column is set 0, so it's disabled, and my thought is that's why it's not in store_group table, is there anyway to solve this?

**Comment by victor-v-rad** [comment]
Hi @Vandeveon 

Normally when you delete a store group, all store views are also deleted automatically because of foreign key STORE_GROUP_ID_STORE_GROUP_GROUP_ID in store table to store_group table. Seems for some reason your M1 > core_store table does not have this key. I would suggest assigning the record from store table to to some existing store group.
