### ISSUE TITLE
3 EAV related tables have wrong references to eav_attribute table

### ISSUE THREAD

**Issue by redboxmarcins** [magento/data-migration-tool#68]
While migrating from CE 1.7.0.2 to EE 2.0.2 

3 tables are still referencing "old" attributes from initial M2 installation instead of referencing current attributes.

This is causing RMA or customer forms to fail with fatal error as forms cannot be created.

Tables are
1. magento_rma_item_form_attribute
2. customer_form_attribute
3. catalog_eav_attribute

**Comment by redboxmarcins** [comment]
I raised this ticket 29 days ago and it is pretty critical. Can I have any update on this please?

**Comment by ilol** [comment]
Hey @redboxmarcins answer in progress. Please wait a little more

**Comment by victor-v-rad** [comment]
Corresponding internal issue was  created to investigate this case

**Comment by ilol** [comment]
MAGETWO-52527

**Comment by 4DallasC** [comment]
The table "catalog_eav_attribute" is not being updated with the imported attribute values and still has the original attributes and their ids in the table.

Not having these values correct, make attributes like the "links_title" and "links_exists" required for all products, not just the downloadable ones.

This issue is so bad, that I am considering dumping the data-migration-tool in favor of a cron.

**Comment by victor-v-rad** [comment]
I have migrated simple product and do not see attribute "links_title" in edit product page. Saving it was without errors

**Comment by ilol** [comment]
Hey! You didn`t respond for a long time. Can I close the issue?
