### ISSUE TITLE
Configurable Product Price blank

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#729]
I have Migrated Magento 1.9.3.7 website in Magento 2.3.3 ,all data is migrated successfully.

I have an issue when checking products in admin->catalog->product and price showing in magento1 but not showing in magento2 in configurable product 

Magento1 Configurable Product Price 
[http://prntscr.com/piwh1a](http://prntscr.com/piwh1a)

Magento2 Configurable Product Price  Screenshot 
[http://prntscr.com/piwhmu](http://prntscr.com/piwhmu)

i want to show configurable product price in frontend 

how can i achieve?

**Comment by victor-v-rad** [comment]
Hi @rakeshdonga 

It is expected behavior. The quote `Please note, you can’t edit the advanced price settings for a configurable product once it’s saved. They can be specified only while creating a new configurable product:` from article
https://amasty.com/knowledge-base/how-to-set-magento-2-configurable-product-price.html

**Comment by rakeshdonga** [comment]
Hi @victor-v-rad 
but i have price showing in admin product gird and frontend showing always 0 price 
and fresh magento2 website in configure product price showing good

**Comment by victor-v-rad** [comment]
The price field does not have 0 but dimmed according to this pic http://prntscr.com/piwhmu

**Comment by victor-v-rad** [comment]
Please share a screenshot of sub products of the configurable product

**Comment by victor-v-rad** [comment]
here is how it looks like in my grid
![configurable product grid](https://user-images.githubusercontent.com/106504/66846022-c1c9a180-ef36-11e9-91b9-e401e84ad9a9.png)

**Comment by rakeshdonga** [comment]
Hello @victor-v-rad 
Child Products (Sub products ) : https://prnt.sc/pjwikg
Configure Product list :https://prnt.sc/pjwiwn
Frontend : https://prnt.sc/pjwl9n
Thanks!!

**Comment by victor-v-rad** [comment]
So the problems with these two products?
![conf price](https://user-images.githubusercontent.com/106504/66962023-9aa5c980-f035-11e9-94c9-b2217bbf696b.png)
And in M1 these two products have higher then 0 price? I cannot reproduce this issue. Can you share more details about price configuration for these subproducts with 0 price or parent configurable product? I mean, maybe they have special price set or have different price for different websites, etc.

**Comment by victor-v-rad** [comment]
I created configurable product on vanilla Magento 2 and see Price field as dimmed 
![Vanila Configur price](https://user-images.githubusercontent.com/106504/66962516-cbd2c980-f036-11e9-814a-17c76271747c.png)
Just like with migrated configurable product.

**Comment by rakeshdonga** [comment]
@victor-v-rad 
in my product grid configurable product price showing but when i am showing in frontend it showing 0 price and in M1 frontend price showing  
https://prnt.sc/pkdqhg

**Comment by pocallaghan** [comment]
The believe frontend of the site determines the price based on the associated simples, I imagine if you look at the "current variations" grid under "Configurations" of the product edit page for the configurable, you'll see that the simple products have a price of 0.

I'd argue the migration should copy the configurable price to the associated simples, however the problem there is there doesn't appear to be feature parity between M1 and M2. In M1 you could associate a simple product with two configurable products and since the price came from the configurable, you could sell the same simple at 2 prices (not sure why you'd do so, but it was possible), as far as I can see this wouldn't be possible in M2, but I'm happy to be told I'm wrong.

I wrote some post migration SQL queries to copy prices over may or may not be useful:
```sql
SET @productEntityTypeId = (SELECT entity_type_id FROM eav_entity_type WHERE entity_type_code = 'catalog_product');
SET @priceAttrId = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'price' AND entity_type_id = @productEntityTypeId);
UPDATE catalog_product_entity_decimal AS a  JOIN (  
	SELECT child_price.value_id, parent_price.value FROM catalog_product_super_link link   
	JOIN catalog_product_entity_decimal parent_price ON link.parent_id = parent_price.entity_id AND parent_price.attribute_id = @priceAttrId  
	JOIN catalog_product_entity_decimal child_price ON link.product_id = child_price.entity_id AND child_price.attribute_id = @priceAttrId  
	WHERE parent_price.value is not null and parent_price.value <> child_price.value ) AS b ON a.value_id = b.value_id 
SET a.value = b.value;
```
