### ISSUE TITLE
After migration Order increment Id is Duplicate 

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#731]
i have migration done magento 1.9.3.7 to magento 2.3.3 with successfully 
in admin i have 5 website and each website i have 3 storeview 
like 

- Dutch 
- French 
- Italian 

when i am place order in Dutch store my order id  is #1000006164
and  i am place order in French store my order id  is #1000006164
also i am place order in Italian store my order id  is #1000006164

why my order id is duplicate in after migration 
in magento 1 order id is like 

1000006164
2000006164
3000006164

and magento 2.3.2 all three store in order id is same 

http://prntscr.com/pk2jrk

**Comment by victor-v-rad** [comment]
Hi @rakeshdonga 

Thank you for reporting this issue. Internal ticket MC-21888 to process it

**Comment by rakeshdonga** [comment]
@victor-v-rad  
i have same issue facing in invoice,shipment ,creditmemo in duplicate id showing

**Comment by victor-v-rad** [comment]
it will be fixed for all

**Comment by victor-v-rad** [comment]
@rakeshdonga  Fixed in 2.3-develop branch. Please test

**Comment by victor-v-rad** [comment]
Prefix issue was fixed in Magento 2 https://github.com/magento/magento2/issues/14063 Now prefix of increment id, like in Magento 1, depends on store view id where order was placed
Store 1 - Store View 1 (default) = order ID 10000001
Store 1 - Store View 2 = order ID 20000001
Store 2 - Store View 3 (default) = order ID 30000001
Store 2 - Store View 4 = order ID 40000001

Previously in Magento 2 for new orders you would have prefix from default store
Store 1 - Store View 1 (default) = order ID 10000001
Store 1 - Store View 2                = order ID 10000002
Store 2 - Store View 3 (default)  = order ID 30000001
Store 2 - Store View 4                = order ID 30000002

BUT in Magento 2 increment id has store id + **9 digits**, in according to \Magento\SalesSequence\Model\Sequence::DEFAULT_PATTERN
whereas Magento 1 increment id has store id + **8 digits**

related #163

**Comment by rakeshdonga** [comment]
@victor-v-rad 
Thanks for solving 
i want to know this issue solved in invoice,shipment and creditmemo also ? 
and if i want to implement in my store then again migtation is need?

**Comment by victor-v-rad** [comment]
Yes fixed for invoice,shipment and creditmemo also. If you do not want to migrate again, you can fix it by changing values for sales_sequence_profile.prefix field and sales_sequence_meta.store_id field in migrated Magento 2 DB. You also can migrate only "SalesIncrement Step" step if you do not changed Magento 2 data after migration. Otherwise it is better to migrate data from scratch.

**Comment by rakeshdonga** [comment]
@victor-v-rad 
i have same issue facing still also same issue facing in invoice,shipment and creditmemo
http://prntscr.com/pm2gk6

i have migration tool install using composer and i have checked my code it is not updated code

**Comment by victor-v-rad** [comment]
Please check that your code has these changes https://github.com/magento/data-migration-tool/commit/09fba3760ae58c368e73314ae65d704613510a64

**Comment by rakeshdonga** [comment]
@victor-v-rad 
Thank you for solving it 
This is working fine my side, and  just i will notify you when i have install data migration tool using composer then above code updated not coming i have manually add it

**Comment by victor-v-rad** [comment]
yes it is because it will be included into next 2.3.4v
