### ISSUE TITLE
Product Name and Meta Title not visible on product view page after migation 

### ISSUE THREAD

**Issue by yogeshkhasturi** [magento/data-migration-tool#732]
### Preconditions

1.  From 1.9.2.4 to 2.3.2 
2. Everything works fine. but the Product details page not showing the Product name and Meta title also Knockout js error in console. http://prntscr.com/pkmiaf

### Steps to reproduce

1.  After migration Open any Product detail page. https://dev.fragrances.com.ng/50-cent-power-edt-100ml-perfume-for-him.html

### Expected result

1.  Product name and meta title should show as its available in admin

### Actual result

1. [Screenshot, logs] http://prntscr.com/pkmjpv

### Additional notes

Error in log for Unknown Theme and noticed Design change and theme table has no entry but "catalog_product_entity_varchar" has entries for old theme. Please help @victor-v-rad

**Comment by yogeshkhasturi** [comment]
@victor-v-rad Any news for this issue ?

**Comment by yogeshkhasturi** [comment]
@victor-v-rad after resaving products one by one its working fine. but only for resaved products

**Comment by victor-v-rad** [comment]
Hi @yogeshkhasturi 

I tried to reproduce the issue on vanilla Magento 1 and Magento 2. When I leave Meta Title empty in Magento 1 product edit page > migrate > Magento 2 gets title from product name. When I fill the  Meta Title filed in Magento 1 > migrate > Magento 2 shows entered Meta Title value. Please provide clear steps to reproduce to the issue you have because on vanilla Magento 1&2 it works fine to me. Maybe there is some extension installed on Magento 1 store which changes behavior of Meta Title and Magento 2 store does not have the same extension installed.

**Comment by yogeshkhasturi** [comment]
Here is clear steps i do. 


1. I migrate Data from Magento 1 to Magento 2 
2. On frontend. i can see the completed data. 
3. Open Any product, No product title and meta title available on the product detail page.
4. I checked in admin if data is available or not. 
5. data was available I just resave the product again. 
6. Then i checked the frontend for the same product. *Title and name both are coming*

Then i tried to resave all products by using * update attribute* in mass action of the grid. 
but unfortunately, that has also a bug reported for 2.3.2 which is only saving the first product out of 100 products that are selected for mass action. 
Please advice us what would be solution for us now. in this stage. ?

Thanks,

**Comment by victor-v-rad** [comment]
I'm sure it is reproducible on **your** environment (Magento 1 and Magento 2) but not on mine clean Magento 1 > migrate > Magento 2.
