### ISSUE TITLE
data-migration mapping error in magento2.3

### ISSUE THREAD

**Issue by arun-magento** [magento/data-migration-tool#762]
[2020-01-01 11:59:37][INFO][mode: data][stage: integrity check][step: EAV Step]:
 started
←[2K100% [============================] Remaining Time: < 1 sec
←[0;33m[2020-01-01 11:59:37][WARNING]: Source fields are not mapped. Document: c
atalog_eav_attribute. Fields: layered_navigation_canonical←[0m

In ErrorHandler.php line 61:

  Notice: Undefined offset: 1 in C:\xampp\htdocs\new_magento\vendor\magento\d
  ata-migration-tool\src\Migration\Step\Eav\Data.php on line 292

In Mysql.php line 173:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Mi
  gration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NA
  ME'

**Comment by victor-v-rad** [comment]
Hi @arun-magento 

Thank you for reporting this issue. To map fields from EAV step use map-eav.xml file or --auto option.
Duplicate entry '1-Migration_Default'  error happens because it is second attempt of migration of data from the beginning. Restore your M2 DB to its initial state and rerun migration

**Comment by arun-magento** [comment]
thank you
