### ISSUE TITLE
Magento 2.3.2 Category Save error

### ISSUE THREAD

**Issue by zakaria-jnh** [magento/data-migration-tool#801]
### Preconditions

1. Migrated DB from 1.9.3.6 to Magento 2.3.2
2. Try to remove assigned category from product

### Expected result

1. The category has been saved

### Actual result

Could not save product "37088" with position 1 to category 3
1. [Screenshot, logs]

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`6qbuhmv_dev`.`catalog_url_rewrite_product_category`, CONSTRAINT `CAT_URL_REWRITE_PRD_CTGR_CTGR_ID_CAT_CTGR_ENTT_ENTT_ID` FOREIGN KEY (`category_id`) REFERENCES `catalog_category_entity` (`en), query was: INSERT INTO `catalog_url_rewrite_product_category` (`url_rewrite_id`,`category_id`,`product_id`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)

**Comment by victor-v-rad** [comment]
Hi @ZAKARIA-14 

Thank you for reporting this issue. I tried to reproduce the issue but it works fine. The error you have might not be caused by the migration tool. Try to find records which exist in catalog_url_rewrite_product_category table and have references to records in catalog_category_entity table. Then recreate these references in catalog_category_entity or remove records from catalog_url_rewrite_product_category

**Comment by zakaria-jnh** [comment]
@victor-v-rad Thanks for your reply, I will try as you suggested
