### ISSUE TITLE
Take into consideration that stores have lived through more than one M1 version

### ISSUE THREAD

**Issue by mzeis** [magento/data-migration-tool#85]
What do I mean by this? An example:

I used the data migration tool on a CE 1.9.2.4 store that was launched in the pre CE 1.9.x era. When executing `bin/magento migrate:data`, I got this error:

    [2016-04-30 19:42:48][INFO][mode: data][stage: integrity check][step: Map Step]: started
    40% [===========>----------------] Remaining Time: 9 secs
    
    
      [Zend_Db_Statement_Exception]
      SQLSTATE[42S02]: Base table or view not found: 1146 Table 'data-migration_dev_magento1.jxsrag_xmlconnect_application' doesn't exist, query was: DESCRIBE `jxsrag_xmlconnect_application`

The reason is that while a store that was launched >= CE 1.9.1.0 never had this table (and others beginning with `xmlconnect_`) created because `Mage_XmlConnect` was deactivated in CE 1.9.1.0, stores which are on the market longer did get that table created and will get this exception when running the migration. I'm betting that many stores will be affected by this.

A solution would be to add `<ignore>` rules for older, not-longer used tables/fields to the mapping files for newer versions. Maybe you have another idea how to handle this or run into more issues because of the same reason, that's why I chose a open issue title deliberately.

**Comment by victor-v-rad** [comment]
Hi, @mzeis 

Yes you are right about adding ignore tags to map files. Though I can't grasp why you got Zend_Db_Statement_Exception instead of something like:
`[2016-03-30 12:40:55][ERROR]: Source documents are not mapped: xmlconnect_application, xmlconnect_config_data ...

  [Migration\Exception]   
  Integrity Check failed  
`
Anyway corresponding internal issue was created to fix your case. Thank you for pointing this out!

**Comment by ilol** [comment]
MAGETWO-52476

**Comment by victor-v-rad** [comment]
@mzeis 
I am closing the issue. Feel free to reopen if it is still actual
